name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Webhook test successful"
